[package]
name = "emvision"
version = "0.1.0"
authors = ["trstruth <trstruth@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.3"
rand = "0.7.2"
